---
title: "Transplants' Open Registry (TxOR)"
---

Transplants Open Registry (TxOR) is a private initiative intended to provide high-quality information about kidney transplantation and based solely on open source resources.

#### Aims

- Collecting open data on transplantation (patients and donors) and make it available, in a transparent and accessible way, to all it may concern.

- Carry out statistical and epidemiological analyzes with open data on transplantation to generate knowledge.

- Defining organ allocation algorithms that guarantee equity of access to a scarce good resource as organs for transplantation.

- Providing accurate, clear and transparent information on transplantation activities in Portugal.

- Enabling decision-making based on evidence of data.

<br>

----------------

## Disclaimer

```{block, type='warning', echo = T}
All applications presented here are intended for research purposes only, not for clinical or commercial use. 

TxOR is a non-profit service to the scientific community, provided on an 'AS-IS' basis without any warranty, expressed or implied. 

The authors can not be held liable in any way for the service provided here.
```

