---
title: "Publications"
---


- Bruno A Lima, Teresa Henriques, Helena Alves. Kidney Allocation Rules Simulator. Transplant International 2021; Vol34 (Suppl. 1): 228 (abstract)

- Bruno A Lima, Teresa Henriques, Helena Alves. Comparing Scores for Predicting Kidney Transplantation Outcomes. Transplant International 2021; Vol34 (Suppl. 1): 228-229 (abstract)

- Bruno A Lima, Helena Alves. [Access to kidney transplantation: a bioethical perspective.](http://www.bbg01.com/cdn/rsc/spnefro/advaccess/253/Nefro342PerspectiveAccesstokidneytransplantation.pdf) Port J Nephrol Hypert 2020; 34(1): 107-109 

- Bruno A Lima, Helena Alves. Comparing the ScandiaTransplant kidney allocation system with a color priority kidney allocation system. Transplant International 2019; Vol32(Suppl 2): 361 (abstract)

- Bruno A Lima, Helena Alves. [Looking for proposals on a new kidney allocation system.](http://www.bbg01.com/cdn/rsc/spnefro/advaccess/181/Nefro331LETTERTOTHEEDITORLookingforproposalsonanewkidneyallocationsystemOK.pdf) Port J Nephrol Hypert 2019; 33(1): 75-76 

- Lima BA, Alves H. [Portuguese calculated panel reactive antibodies online estimator.](https://www.ncbi.nlm.nih.gov/pubmed/30838808) HLA. 2019; 93(6):445-450

- Bruno A Lima, Helena Alves. [Informação disponível sobre transplantação renal: Portugal na União Europeia a 28.](http://repositorio.insa.pt/handle/10400.18/5683) Observações - Boletim Epidemiológico, 7(23), 2018: 67-71

- Bruno A Lima, Helena Alves. [Evaluation of the Portuguese kidney transplant allocation system: comparative results from a simulation.](http://www.bbg01.com/cdn/rsc/spnefro/advaccess/139/06Nefro322Original3.pdf) Port J Nephrol Hypert 32(2), 2018: 201-207 

- Bruno A Lima, Helena Alves. Assessment of a Portuguese Panel Reactive Antibody calculator. HLA 91(5), 2018: pp374 (abstract) 

- Bruno A Lima, Helena Alves. [Seleção do Par Dador-Recetor em Transplante Renal:Resultados Comparativos de uma Simulação.](https://www.actamedicaportuguesa.com/revista/index.php/amp/article/view/8992/5274) Acta Med Port 30(12), 2017: 854-860

- Bruno A Lima. [A call for open data of renal transplantation in Portugal.](http://www.bbg01.com/cdn/rsc/spnefro/pjnh/65/n3_2017_pjnh_01.pdf) Port J Nephrol Hypert 31(3), 2017: 155-157

- Bruno A Lima, Helena Alves. [Atividade do transplante renal de 2003 a 2016: Portugal na União Europeia a 28.](http://repositorio.insa.pt/bitstream/10400.18/4864/1/Boletim_Epidemiologico_Observacoes_N19_2017_artigo3.pdf) Observações - Boletim Epidemiológico, 6(19), 2017: 16-19

- Bruno A Lima, Helena Alves. Comparing the EuroTransplant Kidney Allocation System with a Color Priority  Kidney Allocation System. Transplant International. 30(Suppl 2), 2017: pp208-209 (abstract) 

- Bruno A Lima, Helena Alves. [Evolução da atividade de transplantação renal em Portugal: dados públicos de 2003 a 2015.](http://repositorio.insa.pt/bitstream/10400.18/4713/1/Boletim_Epidemiologico_Observacoes_N18_2017_artigo5.pdf) Observações - Boletim Epidemiológico, 6(18), 2017: 24-27

- Bruno A. Lima. Rationale for a pragmatic randomized controlled trial to test effectiveness of adding rituximab in desensitization protocols of hyper-sensitized kidney transplant candidates. Transplant International. 28(Suppl 24), 2015: pp551 (abstract)

- Bruno A. Lima, Helena Alves. Virtual crossmatch and calculated panel reactive antibody: two sides of the same coin. Transplant International. 28(Suppl 24), 2015: pp813 (abstract)

- Bruno A. Lima, Miguel Mendes, Helena Alves. [Measuring kidney transplantation activity.](http://www.bbg01.com/cdn/clientes/spnefro/pjnh/49/artigo_13.pdf) Port J Nephrol Hypert, 28(2), 2014: 171-176

- Bruno A. Lima, Miguel Mendes, Helena Alves. [Kidney transplant allocation in Portugal.](http://www.bbg01.com/cdn/clientes/spnefro/pjnh/46/artigo_14.pdf) Port J Nephrol Hypert, 27(4), 2013: 313-316

- Bruno A. Lima, Miguel Mendes, Helena Alves. [Hypersensitized candidates to kidney transplantation in Portugal.](http://www.bbg01.com/cdn/clientes/spnefro/pjnh/44/artigo_02.pdf) Port J Nephrol Hypert. 27(2), 2013: 77-81

- Bruno A. Lima, Miguel Mendes, Helena Alves. Applying virtual crossmatch approach in Portuguese kidney transplants. Tissue Antigens. Volume 81, Issue 5, May 2013: pp339 (abstract)

- Bruno A. Lima, Helena Alves. [HLA-A, -C, -B, and -DRB1 allelic and haplotypic diversity in bone marrow volunteer donors from Northern Portugal.](http://www.slideshare.net/balima78/lima-2013) Organs, Tissues & Cells. Volume 16(1), 2013, March: 19-26

- Bruno A. Lima, Miguel Mendes, Helena Alves. [Kidney transplantation in the north of Portugal: donor type and recipient time on dialysis.](http://www.bbg01.com/cdn/clientes/spnefro/pjnh/43/artigo_05.pdf) Port J Nephrol Hypert. 27(1), 2013: 23-30

- Bruno A Lima, Helena Alves. [A Portuguese Living Donor Exchange Program.](http://www.slideshare.net/balima78/otc-2012-lima) Organs, Tissues & Cells. Volume 15(2), 2012, June: 123-129

- Bruno A Lima. [Bone Marrow Volunteer Donors recruitment in Northern Portugal.](http://www.ncbi.nlm.nih.gov/pubmed/?term=22849916) Acta Médica Portuguesa. Volume 24(S2), 2011, December: 301-306

- Bruno A. Lima, Leonídio Dias, António C. Henriques, Helena Alves. [The Portuguese match algorithm in the kidney paired donation program.](http://www.slideshare.net/balima78/otclima-2010-otc) Organs, Tissues & Cells (13), 2010, March: 25-32

- Lima B, Alves H. Cadaveric kidney transplantation waiting list: sociodemographic predictors for single listing. Transplant International, Vol. 20, s2, 2007, September: Page 351 (abstract)

- Lima B, Alves H. Access of double listed patients to cadaveric kidney transplantation. Transplant International, Vol. 20, s2, 2007, September: Page 351 (abstract)

- Lima B, Alves H. Access to renal transplantation in the north of Portugal. Transplant International, Vol. 20 s2, September, 2007: Page 104 (abstract)


